/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.Classes.Men;
import org.example.Classes.Person;
import org.example.Classes.PersonInvocationHandler;

import java.lang.reflect.Proxy;

public class App {


    public static void main(String[] args) {

        Men mohan = new Men("Mohan", 27, "Pune","India");
        ClassLoader mohanClassLoader = mohan.getClass().getClassLoader();
        Class[] interfaces = mohan.getClass().getInterfaces();
        Person proxyMohan = (Person) Proxy.newProxyInstance(
                mohanClassLoader,
                interfaces,
                new PersonInvocationHandler(mohan));
        proxyMohan.introduce(mohan.getName());

    }
}
